"""
Django settings for projeto_estoque project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# Importação das bibliotecas necessárias
from pathlib import Path
import os

# Construa caminhos dentro do projeto como este: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# AVISO DE SEGURANÇA: mantenha a chave secreta usada em produção em segredo!
SECRET_KEY = "django-inseguro-esw503()o3e3%955tx=^9==c*)j(ym9*fpj*sdg5(h6*hd3o&1"

# AVISO DE SEGURANÇA: não execute com debug ativado em produção!
DEBUG = True

ALLOWED_HOSTS = []

# Definição de Aplicações

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "estoque",  # Aplicação "estoque" adicionada ao projeto
]

# Middleware

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Configuração da URL principal do projeto

ROOT_URLCONF = "projeto_estoque.urls"

# Configurações de Templates

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "estoque/templates")
        ],  # Caminho para os templates
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Aplicação WSGI

WSGI_APPLICATION = "projeto_estoque.wsgi.application"

# Configuração do Banco de Dados (MySQL)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "estoquedb",  # Nome do banco de dados no MySQL
        "USER": "root",  # Usuário do MySQL
        "PASSWORD": "",  # Senha do MySQL
        "HOST": "localhost",  # Endereço do servidor MySQL (geralmente localhost)
        "PORT": "3306",  # Porta do servidor MySQL (geralmente 3306)
    }
}

# Configurações de Internacionalização

LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True

# Arquivos Estáticos (CSS, JavaScript, Imagens)

STATIC_URL = "static/"
