# Generated by Django 4.2.6 on 2023-10-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemestoque',
            name='quantidade_disponivel',
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
